[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_req

[dn]
C=TR
ST=Ankara
L=Ankara
O=GULER
OU=IT
CN=*.guler.com

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = *.guler.com
DNS.2 = guler.com